server.port=${PORT:5000}
server.ssl.enabled=${SSL_ENABLED:true}
server.ssl.key-store-type=${KEYSTORE_TYPE:PKCS12}
server.ssl.key-store=${KEYSTORE_PATH:classpath:keystore/ecikeystore.p12}
server.ssl.key-store-password=${KEYSTORE_PASSWORD:123456}
server.ssl.key-alias=${KEY_ALIAS:ecikeypair}